name: YouTube Screenshot Matrix

on:
  workflow_dispatch

jobs:
  capture_screenshots:
    strategy:
      matrix:
        os: [macos-latest, macos-10.15, macos-11.0, macos-12.0, macos-13.0, macos-14.0, windows-latest, windows-2019, windows-2022]
        

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.10'

      - name: Install dependencies
        run: pip install selenium

      - name: Run Selenium script
        run: python my_selenium.py

      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots-${{ matrix.os }}-${{ matrix.python-version }}
          path: .
